Fixed frame metalayer loading memory leaks
Blosc/c-blosc2 pull request #204
Opened 2021-01-27 03:23 UTC by nmoinvaz

2021-01-27 03:29 UTC, nmoinvaz commented
This should also resolve https://oss-fuzz.com/testcase-detail/5985680524181504.

2021-01-27 15:58 UTC, FrancescAlted requested changes
Well done!  I have just a small comment on coding style, but other than this, that's an excellent PR.

2021-01-27 15:58 UTC, FrancescAlted commented on blosc/frame.c
> +  int32_t header_len) {
Watch out indentation. Our style (undocumented) is to align parameters with previous line.

2021-01-28 17:44 UTC, FrancescAlted commented
Curiously enough Win32 complains here too.  Maybe somehow related to #205 ?

2021-01-28 17:45 UTC, FrancescAlted requested changes
I am fine with this as long as win32 issues are addressed.

2021-01-29 08:15 UTC, FrancescAlted approved these changes

2021-01-29 08:15 UTC, merged

2021-01-29 08:16 UTC, FrancescAlted commented
Merged as the Win32 issues are unrelated to this.